version: "3.9"

services:
  db:
    image: postgres:15
    container_name: currencydb
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata_qorix_currency:/var/lib/postgresql/data
    networks:
      - qorix-currency-network

  app:
    build: .
    container_name: qorix-currency
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@currencydb:5432/${POSTGRES_DB}
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    networks:
      - qorix-currency-network

volumes:
  pgdata_qorix_currency:

networks:
  qorix-currency-network: