version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: svaomegaprime/shopify-currency-app:latest
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@currencydb:5432/${POSTGRES_DB}
      NODE_ENV: production
    ports:
      - "4000:4000"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: