# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "41db5a09820fb76a63d8a671d4846d1d"
name = "Qorix Currency Converter"
application_url = "https://qorix-currency.softvenceomega.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/shop_redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [ "https://qorix-currency.softvenceomega.com/api/auth" ]

[app_proxy]
url = "https://qorix-currency.softvenceomega.com/api"
subpath = "currency-converter"
prefix = "apps"
